---
title: Pan BCR analysis
author: University Hospital Basel -- Molecular Diagnostic Unit
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    highlight: zenburn
params:
  panel_df: ""
  output_file: ""
  sample_ID: ""
  lineage_df: ""
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Load libs and data
suppressPackageStartupMessages({
library(knitr)
library(kableExtra)
library(ggplot2)
library(gridExtra)
library(data.table)
library(tidyverse)
library(janitor)
library(LymphocyteSeq)
})
panel_df = params$panel_df
lineage_df = params$lineage_df
lineage_df$filepath = as.character(lineage_df$filepath)
```

### Sample ID: `r params$sample_ID`

## Resultate {.tabset}

### Summary
```{r child='BCR_report/summary_Table.Rmd', include=TRUE}
```

### IGH
```{r child='BCR_report/igh.Rmd', include=TRUE}
```

### IGH lineage
```{r child='BCR_report/igh_lineage_summary.Rmd', include=TRUE}
```

### IGKL
```{r child='BCR_report/igk_l.Rmd', include=TRUE}
```

### IGK_L_lineage
```{r child='BCR_report/igk_l_lineage_summary.Rmd', include=TRUE}
```

## Reporting {-}
### Diagnose
```{r child='BCR_report/diagnose.Rmd', include=TRUE}
```

### Kommentar
```{r child='BCR_report/kommentar.Rmd', include=TRUE}
```

### Methodik
```{r child='BCR_report/methodik.Rmd', include=TRUE}
```

### Eingabe Dateien
```{r}
params$panel_df %>%
  kable("html", digits=3) %>%
  kable_styling(font_size = 7, full_width = FALSE)
```


### R- und Paketversionen
```{r, include=TRUE}
devtools::session_info()
```

